### ISSUE TITLE
I messed up my Librarian presets

### ISSUE THREAD

**Issue by LLToolbox** [ElliotGarbus/Enzo-Editor-and-Librarian#2]
When I first installed this, my Librarian was pull of presets with descriptions.  I'm a newb to all of this and somehow I've lost those.  I can load the sysex version and get the presets back, but I'd like the descriptions back if I can get them.  I've uninstalled and even re-downloaded the zip.
Sorry for posting this as an issue, but I didn't know how else to contact you.

**Comment by ElliotGarbus** [comment]
I have attached a zip of the default library.  This is the initial library that comes with the editor.  unzip this file.   I suggest leaving it in the downloads directory because that will be easy to find.  
On the editor click on the import menu item to import the default_library into your library.
[default_library.zip](https://github.com/ElliotGarbus/Enzo-Editor-and-Librarian/files/4554106/default_library.zip)

**Comment by LLToolbox** [comment]
There they are!  I really appreciate it.  Tools like this add soooo  much
value to the hardware.
I'm new to synths and the visual software interface makes a huge difference
in my learning curve.
The ability to save and recall presets is obviously huge as well.  I got
the link to your software from Andrew @ Meris.

I hope that I can return your generosity some day.

Lance Logan
Duvall, WA
